apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: neat-guppy-python 
  janus-idp.io/tekton: neat-guppy-python
  backstage.io/kubernetes-id: neat-guppy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: neat-guppy-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  