apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: neat-guppy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: neat-guppy-python 
  name: neat-guppy-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: neat-guppy-python
    weight: 100 
